# Generated by Django 4.1 on 2022-08-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('listing_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('user_id', models.IntegerField()),
                ('listing_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='listings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('starting_bid', models.IntegerField()),
                ('imag_url', models.URLField()),
                ('catagory', models.TextField()),
                ('user_id', models.IntegerField()),
                ('sold', models.BooleanField()),
                ('sold_for', models.IntegerField()),
            ],
        ),
    ]
