# Generated by Django 4.1 on 2022-08-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listings_sold_alter_listings_sold_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='current_bid',
            field=models.IntegerField(default=-10),
        ),
    ]
