# Generated by Django 4.1 on 2022-08-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='sold_to',
            field=models.IntegerField(default=-10),
        ),
    ]
