# Generated by Django 4.1 on 2022-08-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listings_current_holder'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='user_name',
            field=models.CharField(default='Anonymus', max_length=100),
        ),
    ]
